# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inbox < Formula
  desc "A fast, beautiful, and distraction-free Gmail client for your terminal."
  homepage "https://github.com/mattrobenolt/inbox"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mattrobenolt/inbox/releases/download/v0.0.1/inbox_0.0.1_darwin_amd64.tar.gz"
      sha256 "999dbd098c263e56caf60d308efce95523fbf322892110290d9b8003c93c2241"

      def install
        bin.install "inbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mattrobenolt/inbox/releases/download/v0.0.1/inbox_0.0.1_darwin_arm64.tar.gz"
      sha256 "bf7bfd0c6ec7e46d5ab8fa766258fe2aa668634a2566c2725ea28b245c70fed7"

      def install
        bin.install "inbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattrobenolt/inbox/releases/download/v0.0.1/inbox_0.0.1_linux_amd64.tar.gz"
      sha256 "edf492ec10871154306def8605d58243c53e1e088282ddce154041c7a05057c4"
      def install
        bin.install "inbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattrobenolt/inbox/releases/download/v0.0.1/inbox_0.0.1_linux_arm64.tar.gz"
      sha256 "eaf5fc62d7667e197ed6b62a39593ce658c498b2b9d63931e590470b5878ac98"
      def install
        bin.install "inbox"
      end
    end
  end

  test do
    system "#{bin}/inbox", "--help"
  end
end
