# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prismacat < Formula
  desc "Themeable truecolor cat for terminal gradients."
  homepage "https://github.com/mattrobenolt/prismacat"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mattrobenolt/prismacat/releases/download/v0.1.0/prismacat_0.1.0_darwin_arm64.tar.gz"
      sha256 "d195e065abe5221dcf531a000dce061aa3359088f73bf1c97a76cdd7120f1bcb"

      define_method(:install) do
        bin.install "prismacat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattrobenolt/prismacat/releases/download/v0.1.0/prismacat_0.1.0_linux_amd64.tar.gz"
      sha256 "abbaf011096279df126534cbb7022558324be59249d258d3ea59fc026b33ec92"
      define_method(:install) do
        bin.install "prismacat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattrobenolt/prismacat/releases/download/v0.1.0/prismacat_0.1.0_linux_arm64.tar.gz"
      sha256 "ea8aa71885d9d942f85c20d6203aeb1cde3b76bc2a0395d909502df9b9a73ebe"
      define_method(:install) do
        bin.install "prismacat"
      end
    end
  end
end
