# This file was generated by GoReleaser. DO NOT EDIT.
cask "appify" do
  name "appify"
  desc "Turn TUI apps into real macOS applications."
  homepage "https://github.com/mattrobenolt/appify"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "appify"

  on_macos do
    on_arm do
      url "https://github.com/mattrobenolt/appify/releases/download/v#{version}/appify_#{version}_darwin_arm64.tar.gz"
      sha256 "41af0add8acec41b17e8abb467382ca8894a86b238cc46d3eddf972236065544"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/appify"]
    end
  end

  # No zap stanza required
end
