# This file was generated by GoReleaser. DO NOT EDIT.
cask "appify" do
  name "appify"
  desc "Turn TUI apps into real macOS applications."
  homepage "https://github.com/mattrobenolt/appify"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "appify"

  on_macos do
    on_arm do
      url "https://github.com/mattrobenolt/appify/releases/download/v#{version}/appify_#{version}_darwin_arm64.tar.gz"
      sha256 "4fac6e848a8de50300a51e9737e5a062e679c20f7363eca34ed39fae80710caa"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/appify"]
    end
  end

  # No zap stanza required
end
