# This file was generated by GoReleaser. DO NOT EDIT.
cask "appify" do
  name "appify"
  desc "Generate macOS .app bundles from terminal commands."
  homepage "https://github.com/mattrobenolt/appify"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "appify"

  on_macos do
    on_arm do
      url "https://github.com/mattrobenolt/appify/releases/download/v#{version}/appify_#{version}_darwin_arm64.tar.gz"
      sha256 "971322806ea1d2dcdc5bfbf237b3eab52d26503e42be65f71a0a296159ed48e4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/appify"]
    end
  end

  # No zap stanza required
end
