# This file was generated by GoReleaser. DO NOT EDIT.
cask "inbox" do
  name "inbox"
  desc "A fast, beautiful, and distraction-free Gmail client for your terminal."
  homepage "https://github.com/mattrobenolt/inbox"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inbox"

  on_macos do
    on_intel do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_darwin_amd64.tar.gz"
      sha256 "51a5bf58c9cab5b6886e7117f4526c35a0186f4892407b1af7cf87c747270c83"
    end
    on_arm do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_darwin_arm64.tar.gz"
      sha256 "535ac8ca26a38575a6b081cdf6d1ef4d3f187c64255b1e750bda8d44c17d7e18"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_linux_amd64.tar.gz"
      sha256 "f45a7060872e4364cfa9b0fb5ab23e38b49f8b81d2aeddb6816971adb78b59e6"
    end
    on_arm do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_linux_arm64.tar.gz"
      sha256 "131381baeebc1497bca7eddf0ceb6f68fd0ff37397ef89f672c0942d8087eebc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/inbox"]
    end
  end

  # No zap stanza required
end
