# This file was generated by GoReleaser. DO NOT EDIT.
cask "inbox" do
  name "inbox"
  desc "A fast, beautiful, and distraction-free Gmail client for your terminal."
  homepage "https://github.com/mattrobenolt/inbox"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inbox"

  on_macos do
    on_intel do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_darwin_amd64.tar.gz"
      sha256 "150e4e15b47b19e71fd3b2bbdf94611316b4ba606db87981a1626154920119cb"
    end
    on_arm do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_darwin_arm64.tar.gz"
      sha256 "4c1674b485705d174480ed684e1d2f60c249ceb541517542a0e37305762921bc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_linux_amd64.tar.gz"
      sha256 "6fa3c63293eab65bdbb92328256fd43d7f443f2b9f0995533256c51580778d8b"
    end
    on_arm do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_linux_arm64.tar.gz"
      sha256 "9308a793ca57fd4bb821ca9b1c377ed2a6b677b9bee5011ee95ae35570c64315"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/inbox"]
    end
  end

  zap trash: [
      "~/Library/Application Support/inbox",
      "~/Library/Caches/inbox",
    ]

end
