# This file was generated by GoReleaser. DO NOT EDIT.
cask "inbox" do
  name "inbox"
  desc "A fast, beautiful, and distraction-free Gmail client for your terminal."
  homepage "https://github.com/mattrobenolt/inbox"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inbox"

  on_macos do
    on_intel do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_darwin_amd64.tar.gz"
      sha256 "aaded71961792e47cfda4cfe4a1a3e7cef5c9af4dec3ef12d6e2a8026f77495d"
    end
    on_arm do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_darwin_arm64.tar.gz"
      sha256 "9ef0688c94ab707cfe8a0f31e5e236aed0996e7fb521c1fae36b52f1e16959ee"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_linux_amd64.tar.gz"
      sha256 "f948ca56186764fd2ef04cbb5bf6c60a4b0cd138f5597014f702e8927c3bf241"
    end
    on_arm do
      url "https://github.com/mattrobenolt/inbox/releases/download/v#{version}/inbox_#{version}_linux_arm64.tar.gz"
      sha256 "3baf33d7975277ef3309931b44a797334bf2024f6cba59731b7ac8c0650edaf7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/inbox"]
    end
  end

  zap trash: [
      "~/Library/Application Support/inbox",
    ]

end
