# This file was generated by GoReleaser. DO NOT EDIT.
cask "prismacat" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "c16096ab396ffee1faebd4d8c485faf90fae5bd3947b4f1cf2b11c9f333065ee"
      url "https://github.com/mattrobenolt/prismacat/releases/download/v#{version}/prismacat_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "274cff2dfbb17bd3d59aae412169034b834ffe20610a981ffbe74758a5377257"
      url "https://github.com/mattrobenolt/prismacat/releases/download/v#{version}/prismacat_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f2cf6e91d91b07ec31eae505fa5c858174998a1978f86b62f8171b70905b3a8"
      url "https://github.com/mattrobenolt/prismacat/releases/download/v#{version}/prismacat_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prismacat"
  desc "Themeable truecolor cat for terminal gradients."
  homepage "https://github.com/mattrobenolt/prismacat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prismacat"

  # No zap stanza required

end
