# This file was generated by GoReleaser. DO NOT EDIT.
cask "prismacat" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "a1a56cd38c7e22063c282b950dc32c2122243d590f7a83b1a5daf1187e14b08b"
      url "https://github.com/mattrobenolt/prismacat/releases/download/v#{version}/prismacat_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d0014697f302ebb9a0f251db82e38ad406ed60a896f32b323c942d1ac7d79016"
      url "https://github.com/mattrobenolt/prismacat/releases/download/v#{version}/prismacat_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d60fc75046d3e36e80f6cfe58d381e113ddb42abad5320b17e51bf3b64b89b78"
      url "https://github.com/mattrobenolt/prismacat/releases/download/v#{version}/prismacat_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prismacat"
  desc "Themeable truecolor cat for terminal gradients."
  homepage "https://github.com/mattrobenolt/prismacat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prismacat"

  # No zap stanza required

end
