# This file was generated by GoReleaser. DO NOT EDIT.
cask "prismacat" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "7996a3f8eb3421eb606870b67d735b55073457589a75e8925362c345de936421"
      url "https://github.com/mattrobenolt/prismacat/releases/download/v#{version}/prismacat_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "670ca819707960cf50cf6db2b5b70a141d4ac30cb6ea8e6a6ff8b69de5a9b99b"
      url "https://github.com/mattrobenolt/prismacat/releases/download/v#{version}/prismacat_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e37f6c81450495a9371eb1f53387bae2a6918c6bf125e6810210e3734054ad16"
      url "https://github.com/mattrobenolt/prismacat/releases/download/v#{version}/prismacat_#{version}_linux_arm64.tar.gz"
    end
  end

  name "prismacat"
  desc "Themeable truecolor cat for terminal gradients."
  homepage "https://github.com/mattrobenolt/prismacat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prismacat"

  # No zap stanza required

end
