# This file was generated by GoReleaser. DO NOT EDIT.
cask "txtar" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "ecc75db675162cebd768c593dffab5d9e4732822cf9919d381117e09deac49aa"
      url "https://github.com/mattrobenolt/txtar/releases/download/v#{version}/txtar_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7f2ad3991cca7fb71368d70adf8609c18475bfbf2995e3e884cc4e3ea2e157fe"
      url "https://github.com/mattrobenolt/txtar/releases/download/v#{version}/txtar_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7ed6f11e2074f240fd4633679784a225d5de483f77996c6834302719d53d3e13"
      url "https://github.com/mattrobenolt/txtar/releases/download/v#{version}/txtar_#{version}_linux_amd64.tar.gz"
    end
  end

  name "txtar"
  desc "Go-style txtar archives for Zig."
  homepage "https://github.com/mattrobenolt/txtar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "txtar"

  # No zap stanza required
end
