# This file was generated by GoReleaser. DO NOT EDIT.
cask "txtar" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "0603240f6ea700ef6a6be6434dfc8b7582a0708b8b82fc294be791dd08bb9773"
      url "https://github.com/mattrobenolt/txtar/releases/download/v#{version}/txtar_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6868754a5276a983c3f9d31cb8c73e4cb66da827e3656cbbae56dee29fc54f6d"
      url "https://github.com/mattrobenolt/txtar/releases/download/v#{version}/txtar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8b2a30dbc781bd3acd7f90bd654b3f5811a54dfdf61e92cd7ad7a68f4e85cd8"
      url "https://github.com/mattrobenolt/txtar/releases/download/v#{version}/txtar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "txtar"
  desc "Go-style txtar archives for Zig."
  homepage "https://github.com/mattrobenolt/txtar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "txtar"

  # No zap stanza required

end
